image: node:18

stages:
  - install
  - test
  - build
  - deploy

# Install
# TODO: пропустить? так как и так будет команда build
backend_install:
  stage: install
  script:
    - echo "backend installing..."


frontend_install:
  stage: install
  script:
    - cd frontend
    - echo "installing frontend deps..."
    - npm ci
    - echo "frontend deps installed"

# Test
backend_test:
  stage: test
  script:
    - echo "backend testing"
    - cd backend
    - npm run test
    - echo "backend tested"

frontend_test:
  stage: test
  script:
    - echo "frontend testing..."
    - cd frontend
    - npm run test
    - echo "frontend tested"

# Build
frontend_build:
  stage: build
  script:
    - echo "frontend building"
    - cd frontend
    - npm run build
    - echo "frontend builded"

# Deploy