image: node:18

stages:
  - test
  - build
  - deploy

# Test
backend_test:
  stage: test
  script:
    - cd backend
    - npm ci
    - npm run test

frontend_test:
  stage: test
  script:
    - cd frontend
    - npm ci 
    - npm run test
  artifacts:
    paths:
      - frontend/node_modules

# Build
frontend_build:
  stage: build
  script:
    - cd frontend
    - npm run build
  artifacts:
    paths:
      - frontend/dist


# Deploy
# TODO: надо создавать в директории файл с ключом, разве нет? Тут надо именно погуглить, как команду rsync использовать с ssh ключами правильно
frontend_deploy:
  image: alpine:3.21
  stage: deploy
  before_script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY"
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/gitlab-ci
    - chmod 600 ~/.ssh/gitlab-ci
  script:
    - echo "frontend deploying"
    # FOCUS: проверка сначала на обычном подключении к серверу по ssh
    - ssh root@185.23.34.22 "ls"
    # - rsync -avz frontend/dist/ root@185.23.34.22:/etc/nginx/sites-available/185.23.34.22/
    - echo "frontend deployed"
