image: node:18

stages:
  - test
  - build
  - deploy

# Test
backend_test:
  stage: test
  script:
    - cd backend
    - npm ci
    - npm run test

frontend_test:
  stage: test
  script:
    - cd frontend
    - npm ci 
    - npm run test
  artifacts:
    paths:
      - frontend/node_modules

# Build
frontend_build:
  stage: build
  script:
    - echo "frontend building"
    - echo $VITE_BACKEND_URL
    - cd frontend
    - ls
    - npm run build
    - echo "frontend built"
  artifacts:
    paths:
      - frontend/dist


# Deploy
frontend_deploy:
  stage: deploy
  script:
    - echo "frontend deploying"
    - rsync -avz frontend/dist/ root@185.23.34.22:/etc/nginx/sites-available/185.23.34.22/
    - echo "frontend deployed"
