image: node:18

stages:
  - test
  - build
  - deploy

# Test
backend_test:
  stage: test
  script:
    - cd backend
    - npm ci
    - npm run test

# frontend_test:
#   stage: test
#   script:
#     - cd frontend
#     - npm ci 
#     - npm run test
#   artifacts:
#     paths:
#       - frontend/node_modules

# Build
# frontend_build:
#   stage: build
#   script:
#     - cd frontend
#     - npm run build
#   artifacts:
#     paths:
#       - frontend/dist


# Deploy
# frontend_deploy:
#   image: alpine:3.21
#   stage: deploy
#   before_script:
#     - apk add --no-cache rsync openssh
#     - mkdir -p ~/.ssh
#     - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
#     - chmod 600 ~/.ssh/id_ed25519
#     - echo "HOST *" > ~/.ssh/config
#     - echo "StrictHostKeyChecking no" >> ~/.ssh/config
#   script:
#     - rsync -avz frontend/dist/ root@185.23.34.22:/var/www/185.23.34.22/

backend_build:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker info
    - echo "backend building"
    - cd backend
    - docker build -t node-app:latest .
    - docker images

# backend_build_and_deploy:
#   image: alpine:3.21
#   stage: deploy
#   before_script:
#     - apk add --no-cache openssh
#     - mkdir -p ~/.ssh
#     - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
#     - chmod 600 ~/.ssh/id_ed25519
#     - echo "HOST *" > ~/.ssh/config
#     - echo "StrictHostKeyChecking no" >> ~/.ssh/config
#   script:
#     - ssh root@185.23.34.22 "cd ~/time-tracker/ && git pull && cd backend/ && docker compose up --build -d"

