image: node:18

stages:
  - test
  - build
  - deploy

# Test
backend_test:
  stage: test
  script:
    - cd backend
    - npm ci
    - npm run test

frontend_test:
  stage: test
  script:
    - cd frontend
    - npm ci 
    - npm run test

# Build
frontend_build:
  stage: build
  script:
    - echo "frontend building"
    - echo $VITE_BACKEND_URL
    - cd frontend
    - npm ci
    - npm run build
    - echo "frontend built"

# TODO: установить в артефакт сбилженный фронт, чтобы в job деплоя его использовать (убедиться сначала с помощью команды ls)

# TODO: задеплоить фронтенд
# Deploy