image: node:18

stages:
  - install # TODO: delete
  - test
  - build
  - deploy

# Test
backend_test:
  stage: test
  script:
    - echo "backend testing"
    - cd backend
    - npm ci
    - npm run test
    - echo "backend tested"

frontend_test:
  stage: test
  script:
    - echo "frontend testing..."
    - cd frontend
    - npm ci 
    - npm run test
    - echo "frontend tested"

# Build
# TODO: установить .env переменные?
frontend_build:
  stage: build
  script:
    - echo "frontend building"
    - cd frontend
    - npm ci
    - npm run build
    - cd dist
    - ls
    - echo "frontend built"

# Deploy