image: node:18

stages:
  - test
  - build
  - deploy

# Test
backend_test:
  stage: test
  script:
    - cd backend
    - npm ci
    - npm run test

frontend_test:
  stage: test
  script:
    - cd frontend
    - npm ci 
    - npm run test
  artifacts:
    paths:
      - frontend/node_modules

# Build
frontend_build:
  stage: build
  script:
    - cd frontend
    - npm run build
  artifacts:
    paths:
      - frontend/dist


# Deploy
# TODO: надо создавать в директории файл с ключом, разве нет?
frontend_deploy:
  image: alpine:3.21
  stage: deploy
  before_script:
    - apk add --no-cache rsync openssh
  script:
    - echo "frontend deploying"
    # - echo $SSH_PRIVATE_KEY
    - rsync -avz frontend/dist/ root@185.23.34.22:/etc/nginx/sites-available/185.23.34.22/
    - echo "frontend deployed"
