version: '3'

services:
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  node_app:
    build: ./backend
    ports:
      - '8001:8000'
    environment:
      - PORT=8000
      - MONGO_URL=mongodb://mongo_db:27017/time_tracker
      - ACCESS_TOKEN_SECRET=asdaksldj23123
      - REFRESH_TOKEN_SECRET=zc,43sdszxckl;;
    depends_on:
      - mongo_db

  react_app:
    build: ./frontend
    ports:
      - '3000:5173'
    environment:
      - VITE_BACKEND_URL=http://localhost:8001
    depends_on:
      - node_app

volumes:
  mongo_db: {}
