version: '3'

services:
  mongo_db:
    container_name: database_container
    image: mongo:8.0.5
    volumes:
      - mongo_db:/data/db

  redis:
    image: redis:7.2.8
    volumes:
      - ./run/redis_volume_data:/data
    ports:
      - 6379:6379

  node_app:
    build: .
    ports:
      - '8003:8000'
      - '9229:9229'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=8000
      - MONGO_URL=mongodb://mongo_db:27017/time_tracker
      - ACCESS_TOKEN_SECRET=asdaksldj23123
      - REFRESH_TOKEN_SECRET=zc,43sdszxckl;;
    depends_on:
      - mongo_db
    command: npm run dev

volumes:
  mongo_db: {}
