version: '3'

services:
  mongo_db:
    container_name: database_container
    image: mongo:8.0.5
    volumes:
      - mongo_db:/data/db

  redis:
    image: redis:7.2.8
    volumes:
      - ./run/redis_volume_data:/data
    ports:
      - 127.0.0.1:6379:6379

  rabbitmq:
    image: rabbitmq:3.13-management
    restart: unless-stopped
    ports:
      - '5672:5672' # AMQP
      - '15672:15672' # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin123
      RABBITMQ_DEFAULT_PASS: admin123
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - ./run/rabbitmq_data:/var/lib/rabbitmq

  node_app:
    build: .
    ports:
      - '8003:8000'
      - '9229:9229'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # чтобы локальный node_moduls не был связан с node_modules в контейнере
      - uploads:/usr/uploads
    depends_on:
      - rabbitmq
      - mongo_db
    command: npm run dev

  worker:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # чтобы локальный node_moduls не был связан с node_modules в контейнере
    depends_on:
      - rabbitmq
    command: npm run startWorker
    # command: tail -f /dev/null

volumes:
  mongo_db: {}
  uploads:
